"""
Headless notification-count scraper for 抖音 / 小红书 / 视频号.
Reuses Playwright storage_state cookie files generated by `sau login`.
"""

from __future__ import annotations

import json
import asyncio
import importlib.util
import threading
from pathlib import Path

from patchright.async_api import async_playwright

from config import account_file, launch_kwargs, SAU_ROOT, MESSAGING_URLS, PLATFORM_LABELS

# ---------------------------------------------------------------------------
# Cookie helpers
# ---------------------------------------------------------------------------


def _cookie_dict(account_file: Path) -> dict[str, str]:
    """Convert Playwright storage_state cookies into a plain name→value dict."""
    if not account_file.exists():
        return {}
    data = json.loads(account_file.read_text(encoding="utf-8"))
    return {c["name"]: c["value"] for c in data.get("cookies", [])}


def _set_init_script(context):
    """Reuse social-auto-upload's stealth script injection."""
    spec = importlib.util.spec_from_file_location(
        "base_social_media",
        str(SAU_ROOT / "utils" / "base_social_media.py"),
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.set_init_script(context)


# ---------------------------------------------------------------------------
# Per-platform scrapers
# ---------------------------------------------------------------------------

async def _scrape_douyin(account_name: str) -> dict:
    cookie_path = account_file("douyin", account_name)
    if not cookie_path.exists():
        return {"logged_in": False, "counts": {}, "error": "cookie 文件不存在，请先登录"}

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(**launch_kwargs(headless=True))
        try:
            context = await browser.new_context(storage_state=str(cookie_path))
            context = await _set_init_script(context)
            page = await context.new_page()
            await page.goto(
                "https://creator.douyin.com/creator-micro/home", timeout=30000
            )
            await page.wait_for_timeout(3000)

            # Detect login state
            if "/login" in page.url:
                return {"logged_in": False, "counts": {}, "error": "抖音 cookie 已过期，请重新登录"}

            counts: dict[str, int] = {}

            # Top-nav notification bell badge
            badge_selectors = [
                'span.notify-num',
                'span.badge',
                'span[class*="badge"]',
                'sup.ant-badge-count',
                'span.ant-badge-count',
                'span[class*="unread"]',
                'span[class*="count"]',
            ]
            for sel in badge_selectors:
                try:
                    el = page.locator(sel).first
                    if await el.count() and await el.is_visible():
                        text = (await el.text_content() or "").strip()
                        if text.isdigit():
                            counts["notifications"] = int(text)
                            break
                except Exception:
                    continue

            # Sidebar / specific tabs
            sidebar_items = {
                "私信": "messages",
                "评论": "comments",
                "@我": "mentions",
                "点赞": "likes",
                "通知": "notifications",
            }

            for label, key in sidebar_items.items():
                try:
                    item = page.get_by_text(label, exact=True).first
                    if await item.count():
                        parent = item.locator("..")
                        badge = parent.locator('span[class*="badge"], span[class*="count"], span[class*="num"]').first
                        if await badge.count():
                            text = (await badge.text_content() or "").strip()
                            if text.isdigit():
                                counts[key] = int(text)
                except Exception:
                    continue

            return {"logged_in": True, "counts": counts}

        except Exception as exc:
            return {"logged_in": False, "counts": {}, "error": str(exc)}
        finally:
            await browser.close()


async def _scrape_xiaohongshu(account_name: str) -> dict:
    cookie_path = account_file("xiaohongshu", account_name)
    if not cookie_path.exists():
        return {"logged_in": False, "counts": {}, "error": "cookie 文件不存在，请先登录"}

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(**launch_kwargs(headless=True))
        try:
            context = await browser.new_context(storage_state=str(cookie_path))
            context = await _set_init_script(context)
            page = await context.new_page()
            await page.goto("https://creator.xiaohongshu.com", timeout=30000)
            await page.wait_for_timeout(3000)

            if "/login" in page.url:
                return {"logged_in": False, "counts": {}, "error": "小红书 cookie 已过期，请重新登录"}

            counts: dict[str, int] = {}

            # Badge elements in sidebar or top nav
            badge_candidates = page.locator(
                'span[class*="badge"], span[class*="count"], span[class*="num"], '
                'span[class*="unread"], div[class*="badge"], div[class*="unread"]'
            )
            for i in range(await badge_candidates.count()):
                try:
                    el = badge_candidates.nth(i)
                    if await el.is_visible():
                        text = (await el.text_content() or "").strip()
                        if text.isdigit() and int(text) > 0:
                            # Try to infer what the badge is for from nearby text
                            counts[f"badge_{i}"] = int(text)
                except Exception:
                    continue

            # Sidebar text labels — try to associate counts with labels
            sidebar_labels = {
                "私信": "messages",
                "评论": "comments",
                "互动": "interactions",
                "粉丝": "followers",
                "通知": "notifications",
            }

            for label, key in sidebar_labels.items():
                try:
                    item = page.get_by_text(label).first
                    if await item.count():
                        parent = item.locator("..")
                        badge = parent.locator(
                            'span[class*="badge"], span[class*="count"], '
                            'span[class*="num"], span[class*="unread"]'
                        ).first
                        if await badge.count():
                            text = (await badge.text_content() or "").strip()
                            if text.isdigit():
                                counts[key] = int(text)
                except Exception:
                    continue

            return {"logged_in": True, "counts": counts}

        except Exception as exc:
            return {"logged_in": False, "counts": {}, "error": str(exc)}
        finally:
            await browser.close()


async def _scrape_tencent(account_name: str) -> dict:
    cookie_path = account_file("tencent", account_name)
    if not cookie_path.exists():
        return {"logged_in": False, "counts": {}, "error": "cookie 文件不存在，请先登录"}

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(**launch_kwargs(headless=True))
        try:
            context = await browser.new_context(storage_state=str(cookie_path))
            context = await _set_init_script(context)
            page = await context.new_page()
            await page.goto(
                "https://channels.weixin.qq.com/platform/post/list", timeout=30000
            )
            await page.wait_for_timeout(3000)

            if "/login" in page.url:
                return {"logged_in": False, "counts": {}, "error": "视频号 cookie 已过期，请重新登录"}

            counts: dict[str, int] = {}

            # Top nav: look for "互动消息" with a red dot or badge
            interaction_items = [
                "互动消息",
                "消息",
                "评论",
                "私信",
            ]
            for label in interaction_items:
                try:
                    item = page.get_by_text(label).first
                    if await item.count() and await item.is_visible():
                        parent = item.locator("..")
                        badge = parent.locator(
                            'span[class*="badge"], span[class*="dot"], '
                            'span[class*="count"], span[class*="num"], '
                            'span[class*="unread"], span[class*="red"], '
                            'sup, i[class*="dot"], i[class*="red"]'
                        ).first
                        if await badge.count():
                            text = (await badge.text_content() or "").strip()
                            if text.isdigit() and int(text) > 0:
                                counts[label] = int(text)
                            else:
                                # Red dot without number counts as 1+
                                badge_html = (await badge.inner_html() or "").lower()
                                parent_html = (await parent.inner_html() or "").lower()
                                if any(
                                    c in badge_html + parent_html
                                    for c in ("red", "dot", "unread")
                                ):
                                    counts[label] = -1  # -1 = "有未读但无数值"
                except Exception:
                    continue

            return {"logged_in": True, "counts": counts}

        except Exception as exc:
            return {"logged_in": False, "counts": {}, "error": str(exc)}
        finally:
            await browser.close()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

PLATFORM_SCRAPERS = {
    "douyin": _scrape_douyin,
    "xiaohongshu": _scrape_xiaohongshu,
    "shipinhao": _scrape_tencent,
    "tencent": _scrape_tencent,
}


async def get_all_notifications(
    accounts: list[dict],  # each: {"platform": "douyin", "loginName": "xxx"}
) -> list[dict]:
    """Scrape notifications for all accounts in parallel."""
    tasks = []
    for acc in accounts:
        platform = acc.get("platform", "")
        login_name = acc.get("loginName", "")
        scraper = PLATFORM_SCRAPERS.get(platform)
        if scraper and login_name:
            tasks.append(_scrape_one(acc, scraper, login_name))

    if not tasks:
        return []

    results = await asyncio.gather(*tasks, return_exceptions=True)
    output = []
    for r in results:
        if isinstance(r, Exception):
            output.append({"logged_in": False, "counts": {}, "error": str(r)})
        else:
            output.append(r)
    return output


async def _scrape_one(acc: dict, scraper, login_name: str) -> dict:
    result = await scraper(login_name)
    result["platform"] = acc.get("platform", "")
    result["alias"] = acc.get("alias", "")
    result["loginName"] = login_name
    return result


def get_notifications_sync(accounts: list[dict]) -> list[dict]:
    """Synchronous wrapper for use in non-async code (e.g. server.py)."""
    return asyncio.run(get_all_notifications(accounts))


# ---------------------------------------------------------------------------
# Browser-open helper — opens messaging page in a headed browser window
# ---------------------------------------------------------------------------


async def _open_and_keep_alive(platform: str, account_name: str, account_file: Path) -> None:
    """Launch a headed browser and leave it open so the user can interact.
    Never closes — the user closes the window manually."""
    target_url = MESSAGING_URLS.get(platform, "")
    if not target_url:
        return

    pw = await async_playwright().start()
    browser = await pw.chromium.launch(**launch_kwargs(headless=False))
    context = await browser.new_context(
        storage_state=str(account_file), no_viewport=True
    )
    context = await _set_init_script(context)
    page = await context.new_page()
    await page.goto(target_url, timeout=30000)
    # Browser stays open; user interacts and closes it manually.
    # We intentionally never call browser.close() or pw.stop() here.


def open_messaging_page_sync(platform: str, account_name: str) -> dict:
    """Fire-and-forget: open messaging page in headed browser, return immediately."""
    cookie_path = account_file(platform, account_name)
    if not cookie_path.exists():
        return {
            "ok": False,
            "error": f"cookie 文件不存在: {cookie_path}，请先登录",
        }

    target_url = MESSAGING_URLS.get(platform, "")
    if not target_url:
        return {"ok": False, "error": f"未知平台: {platform}"}

    def _bg_run() -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(
                _open_and_keep_alive(platform, account_name, cookie_path)
            )
        except Exception:
            pass  # Browser already shown or error; don't crash the thread

    t = threading.Thread(target=_bg_run, daemon=True)
    t.start()

    return {
        "ok": True,
        "platform": platform,
        "account": account_name,
        "message": f"已打开 {PLATFORM_LABELS.get(platform, platform)} 页面 ({target_url})，请在新窗口中操作。操作完成后可关闭窗口。",
    }
